### ISSUE TITLE
Página web para explicar Locha

### ISSUE THREAD

**Issue by rdymac** [btcven/locha#1]
Necesitamos una página web sencilla tipo landing page donde podamos explicar el proyecto y cada parte del mismo.

http:// Locha.io

**Comment by grunch** [comment]
En el sitio se debe explicar la idea del proyecto y como se planea concretar.

En este issue podemos ir comentando ideas y de acá mismo sacar la info que tendrá el site

**Comment by medied** [comment]
Estoy viendo como colaborar con el proyecto y por aqui pudiese empezar, ¿[esta pagina](https://locha.io/) es donde piensan empezar?

**Comment by Lyezerg** [comment]
Buenas queridos amigos, al equipo de locha.io les deje un msj por twitter, espero le dediquen tiempo para organizar una pequeña reunion!  Saudos desde HeathToken

**Comment by luisan00** [comment]
Working on it

**Comment by rdymac** [comment]
https://locha.io tiene un tiempo publicada. La documentación se está maquetando para enlazarla desde esa web.
