### ISSUE TITLE
Ability to contact you privately

### ISSUE THREAD

**Issue by NyamiDev** [btcven/locha#178]
Hi,

I think your project is brilliant, desperately needed and would love to learn more. I would however like to setup secure encrypted communications with your team rather than just sending a normal email. May I suggest you add to your website a PGP key for those who wish to email you securely, and/or contact details for another tool like Matrix/Signal/Threema. You could also have a Protonmail/Tutanota/Ctemplar email which by default is encrypted if the person wanting to communicate with you also uses those tools. 

Best of luck with an incredibly important company.

Yours, 

NyamiDev

**Comment by Talkless** [comment]
> Best of luck with an incredibly important company.

+1. I too want this to happen. And some PGP-or-whatever-based P2P chat working on LochaMesh would be awesome.

By the way, there's https://github.com/btcven/locha-mesh-chat app, but I need something to be used on desktop Linux.
