### ISSUE TITLE
FAQ Update Request

### ISSUE THREAD

**Issue by NyamiDev** [btcven/locha#179]
Update to FAQ request

Please could you provide an example in the FAQ of how a purchaser of say 3 Turpials would use these tools right now in the real word to connect to the internet. Give an example, lets say you are in Johannesburg and the power goes out, who do you actually connect to? Do you have to find peers online before the internet goes out, ie prepare first, therefore decide who will be the actuall internet gateway etc. What I mean is can you provide a worked real world example. What if I am the only person in Joberg that has locha mesh tools? Will that be of no use? Can you suggest a minimum viable network setup, so one could say encourage 5 friends to get involved and build a test network prior to it being needed in anger. From reading the FAQ I would end up with some clever devices but not know who to connect to. Perhaps elaborate on this?

Secondly, can you provide a map of giving an idea where the network is rolled out already? I know this can change and the whole idea is that it is private, flexible and can start and stop at any time. It would just be nice to know that there is potential network effect in the area you are considering so you could piggy back on the existing infrastructure. 

Thirdly, is there a way of contacting prospective peers, via some private social media group, on Matrix for example?

Thank you,

NyamiDev

**Comment by Talkless** [comment]
> Can you suggest a minimum viable network setup, so one could say encourage 5 friends to get involved and build a test network prior to it being needed in anger.

+1 . I too really miss more use case examples. Connecting bitcoind is cool and stuff, but we really need more down to earth, practical use cases.

Maybe some p2p chat protocol could be used to find other nearby Locha users and create chat room in your city/district? That would actually motivate to make/buy devices and spread the world among friends and neighbours, local FOSS community, etc.
