### ISSUE TITLE
Resume Tupial manufacturing in parnership with other Bitcoin-related HW manufacturers

### ISSUE THREAD

**Issue by Talkless** [btcven/locha#180]
There's Coinkite, that develops OpenDime and Coldcard, SatoshiLabs that develops Trezor wallet, and there are others.
 
Maybe partnership with them could make LochaMesh happen? I believe @rdymac mentioned in one of the interviews that by fact that company was running on developers, not businessman or sales people, LochaMesh company failed (more or less? Please correct me if I'm wrong).

**Comment by king4logy** [comment]
That's what i would've suggesting too...since those guise already have audiences that need technology such as this...collabo with them wouldn't be a bad thing.
