### ISSUE TITLE
Improve documentation for contributors and how to build a DIY version 

### ISSUE THREAD

**Issue by rdymac** [btcven/locha#26]
This issue is related to the CCS proposal: https://locha.io/monero

--

Identify docs and links that need work and new ones that may need to be created.

- We need to repeat the step by step setup for each OS ([as we did](https://github.com/MeshedPotato/Project-Plans/blob/master/hardware/LochaMesh/getting-started.md) for the Windows instructions).

- This README needs to be revamped: https://github.com/btcven/turpial-firmware ✓

- This README needs to be revamped: https://github.com/btcven/radio-firmware ✓

- Double check repos that may need to be removed from https://github.com/btcven for clarity. ✓

- Add a table of comparison with all the existing mesh techs [in documents](https://github.com/btcven/locha/tree/master/documents) or documentation.

**Comment by luisan00** [comment]
up

**Comment by luisan00** [comment]
PR: #120, Add Authors file

**Comment by luisan00** [comment]
This closes #165

**Comment by luisan00** [comment]
PR done. It will be closed if no further activity occurs

**Comment by luisan00** [comment]
Done
