### ISSUE TITLE
Broken hyperlink on github page

### ISSUE THREAD

**Issue by GlenCooper** [btcven/locha#27]
![D231AF32-E6AB-4F17-81B3-F67431BB86AB](https://user-images.githubusercontent.com/967793/76251618-b052a000-621d-11ea-8967-2b5b7e672efb.jpeg)

![715FAB9E-A957-45D3-AA23-EF62550BFE51](https://user-images.githubusercontent.com/967793/76251644-bfd1e900-621d-11ea-86c8-54cdd98f6231.png)

**Comment by GlenCooper** [comment]
Please fix the hyperlink for Telegram

**Comment by jeandudey** [comment]
Fixed, thanks for taking the time!
