### ISSUE TITLE
One file per chapter.

### ISSUE THREAD

**Issue by luisan00** [btcven/locha#39]
## The problem:
One file for all the documentation will be a huge problem for many reviewers, for example a simple _PR_ can be a headache.

## Solution:
Break the document into chapters, this way each chapter will be a document. this will facilitate the reviews and _PRs_

### Keep in mind:
For future translations to other languages, the name of the files will be language agnostic. For example, each chapter can be named _chapter_1.md_ for the chapter "one", _chapter_2.md_ for chapter "two", and so.

**Comment by rdymac** [comment]
> chapter_1.md for the chapter "one", chapter_2.md for chapter "two"

I second this suggestion of using more generic names for the files according to its content. If a file has sub content, it could still use the same format: chapter_6_4.md for the 6.4 point of the 6th chapter if it is too long by itself to be in just one file.  chapter_6-6-3.md , chapter_6_4.md , chapter_6_5-6_9.md

**Comment by gustavosinbandera1** [comment]
for now I have created this branch  to show you how the document looks, just let me know if really we need to change the name for each file or maybe in the actual name file could  work.

https://github.com/btcven/locha/tree/feature/slice_docummentation/documentation/ES

**Comment by luisan00** [comment]
Yes the file names will be chapter_1.md, chapter_2.md, etc or chapter_3_2.md for sub-chapters, so the naming rules are;
**chapter_[chapter_number]_[sub-chapter_number].md**

**Comment by gustavosinbandera1** [comment]
this is ready now
