### ISSUE TITLE
 capítulo 8,numeración de secciones inconsistente

### ISSUE THREAD

**Issue by luisan00** [btcven/locha#44]
Hay una inconsistencia en la numeración del capítulo 8:
https://github.com/btcven/locha/blob/dev/documentation/ES/chapter_8.md

Concretamente de la seccion [8.5 Tabla de rutas](https://github.com/btcven/locha/blob/dev/documentation/ES/chapter_8.md#85-tabla-de-rutas) salta a la [8.7 Router Client Set](https://github.com/btcven/locha/blob/dev/documentation/ES/chapter_8.md#87-router-client-set)

Si esto se debe a una acción intencionada bien, si no hay que re-enumerar las secciones y sub-secciones posteriores a la _8.5 Tabla de rutas_

**Comment by gustavosinbandera1** [comment]
ready now
