### ISSUE TITLE
Documentación ES - Revisión, comentarios, y posibles ediciones 

### ISSUE THREAD

**Issue by stephien** [btcven/locha#46]
Revisión de los capítulos 1 al ~6~ 12

- Correciones de errores de tipeo y gramaticales.
- Revisión y cambio de muletillas.
- Revisión de títulos, subtítulos, y enumeraciones.
 
Abierto a colaboraciones y sugerencias.

**Comment by luisan00** [comment]
Titulos y Subtitulos:
 El encabezamiento de cada archivo no aporta información y es redundante, ejemplo:
```
# Capitulo 1
# 1. Introducción y Objetivos
``` 
```
# Capitulo 2
# 2. Trabajo propuesto
```
Simplemente lo dejaria en:
```
# 1. Introducción y Objetivos
``` 
```
# 2. Trabajo propuesto
```
y así en cada archivo `chapter_xx.md`

**Comment by gustavosinbandera1** [comment]
La intension de usar la palabra # Capitulo 1, #Capitulo x, es debido a que se pretende llenar esos espacion con un resumen de lo que trata cada subcapitulo. pero es opcional

**Comment by gustavosinbandera1** [comment]
utilizar <h1> dentro de markdown lo que me permite es  que el title no aparezca en el indece del contenido

**Comment by stephien** [comment]
PR de ediciones de capítulos 1 al 6:

- Cap 1 #60
- Cap 2 #61
- Cap 3 #64
- Cap 4 #65
- Cap 5 #69 (approved)
- Cap 6 #70

Fueron corregidos errores de tipeo y gramaticales. Algunos conceptos fueron editados para resumir texto y facilitar la lectura manteniendo la idea. De ser aprobado como versión, paso a traducir.

**Comment by luisan00** [comment]
## Listos para revisión.
- capítulo 9
- capítulo 11
## En proceso.
- capítulo 12

**Comment by luisan00** [comment]
All related work is done, closing in 2, 1, .....
