### ISSUE TITLE
standalone device

### ISSUE THREAD

**Issue by ulrichard** [btcven/locha#6]
A standalone wallet device would be cool.
Something like the case wallet, but without the centralized server part, and with communication over the mesh instead of GPRS.

**Comment by luisan00** [comment]
@ulrichard , what is the "case wallet" example you are referring to?

We thought about a standalone airgapped hardware before, but we are now focusing on the Locha Mesh Turpial devices specifically. The new Turpial device revision use a IPv6 stack in the long range radio interface, so practically any service that currently runs over the Internet can be used within the Locha Mesh.

**Comment by ulrichard** [comment]
The Case was a standalone Bitcoin hardware wallet. The great thing was that it didn't need a separate internet connected phone, because it had a GSM connection built in. 
The bad part was that it relied on a centralized server that was shut down after two or three years.
