### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by xmrhaelan** [btcven/locha#9]
**Is your feature request related to a problem? Please describe.**
For the prototypes that have been tested successfully, did anyone run performance benchmarks?

**Describe the solution you'd like**
Would be great to have benchmarks available for any MCU or radio module that is tested, as well as a way for people who test new MCUs and radio modules to add their benchmarks to a list here. This would help enhance future builds and make it easier for people to decide what hardware to use.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by luisan00** [comment]
It's a early stage for benchmarking but maybe a great idea to be considered in a near future :+1:

**Comment by luisan00** [comment]
up
